# Generated by Django 2.0.6 on 2018-06-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created='True')),
                ('name', models.CharField(max_length=20)),
                ('comments', models.TextField(max_length=1000)),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
            ],
        ),
    ]
