# Generated by Django 2.0.6 on 2018-06-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todaycomment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment_list',
        ),
        migrations.RenameField(
            model_name='comment_list',
            old_name='comments',
            new_name='comment_text',
        ),
    ]
