# Generated by Django 2.0.6 on 2018-07-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todaycomment', '0002_auto_20180630_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_list',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment_list',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
