# Generated by Django 2.0.6 on 2018-07-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
