# Generated by Django 2.0.6 on 2018-07-07 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_article_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edited_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Latest edited date'),
            preserve_default=False,
        ),
    ]
