# Generated by Django 2.0.6 on 2018-07-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20180709_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('board_description', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
    ]
