# Generated by Django 2.0.6 on 2018-07-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_article_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='board',
            new_name='board_name',
        ),
    ]
