# Generated by Django 2.0.6 on 2018-07-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_blueboard_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='board_name',
        ),
        migrations.AlterField(
            model_name='article',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Latest edited date'),
        ),
        migrations.DeleteModel(
            name='BlueBoard',
        ),
    ]
