# Generated by Django 2.0.6 on 2018-07-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='up_down',
            field=models.BooleanField(default=True),
        ),
    ]
