# Generated by Django 2.0.6 on 2018-07-19 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_vote_up_down'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='vote',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='boards.Vote'),
            preserve_default=False,
        ),
    ]
