# Generated by Django 2.0.6 on 2018-07-22 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_auto_20180720_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
