# Generated by Django 2.0.6 on 2018-07-29 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_auto_20180729_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Article'),
        ),
    ]
