# Generated by Django 2.0.6 on 2018-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_auto_20180730_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
