# Generated by Django 2.0.6 on 2018-07-31 09:02

from django.db import migrations, models
import tutorialPoll.settings


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0023_attachment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=tutorialPoll.settings.custom_uploaded_filepath),
        ),
    ]
