# Generated by Django 2.1.5 on 2019-01-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0025_auto_20190113_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
