# Generated by Django 2.1.5 on 2019-01-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0027_auto_20190114_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='has_higher_board',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='higher_board',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
