# Generated by Django 2.1.5 on 2019-01-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0028_auto_20190114_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserprofile',
            name='introduction',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='additionaluserprofile',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
