# Generated by Django 2.1.5 on 2019-01-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0030_additionaluserprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
