# Generated by Django 2.1.5 on 2019-01-15 16:29

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.ftp
import tutorialPoll.custom_upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0031_board_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True)),
                ('file', models.FileField(storage=storages.backends.ftp.FTPStorage(), upload_to=tutorialPoll.custom_upload_path.custom_uploaded_filepath_debug_board_image)),
                ('uploaded', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='image_file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.BoardImage'),
        ),
    ]
