# Generated by Django 2.1.5 on 2019-01-15 16:35

from django.db import migrations, models
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0032_auto_20190116_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardimage',
            name='file',
            field=models.FileField(storage=storages.backends.ftp.FTPStorage(), upload_to='testingBoardImage/test/'),
        ),
    ]
