# Generated by Django 2.1.5 on 2019-01-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0033_auto_20190116_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='creator_public',
            field=models.BooleanField(default=True),
        ),
    ]
