# Generated by Django 2.1.5 on 2019-01-15 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.ftp
import tutorialPoll.custom_upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0034_board_creator_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='board',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='boards.Board'),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articleiplog',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boards.Article'),
        ),
        migrations.AlterField(
            model_name='articleiplog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='higher_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boards.Board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='image_file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='boards.BoardImage'),
        ),
        migrations.AlterField(
            model_name='boardimage',
            name='file',
            field=models.FileField(storage=storages.backends.ftp.FTPStorage(), upload_to=tutorialPoll.custom_upload_path.custom_uploaded_filepath_debug_board_image),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='boards.Article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentiplog',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boards.Comment'),
        ),
        migrations.AlterField(
            model_name='commentiplog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
