# Generated by Django 2.1.5 on 2019-01-15 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0035_auto_20190116_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='higher_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='higher_board_related', to='boards.Board'),
        ),
    ]
