# Generated by Django 2.1.5 on 2019-01-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0036_auto_20190116_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='has_lower_board',
            field=models.BooleanField(default=False),
        ),
    ]
