# Generated by Django 2.1.5 on 2019-01-21 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.ftp
import tutorialPoll.custom_upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0038_auto_20190118_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additionaluserprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardimage',
            name='file',
            field=models.FileField(storage=storages.backends.ftp.FTPStorage(), upload_to=tutorialPoll.custom_upload_path.custom_uploaded_filepath_deploy_board_image),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='file',
            field=models.ImageField(storage=storages.backends.ftp.FTPStorage(), upload_to=tutorialPoll.custom_upload_path.custom_uploaded_filepath_deploy_board_image),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userprofileimage', to=settings.AUTH_USER_MODEL),
        ),
    ]
