# Generated by Django 2.1.5 on 2019-01-22 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0039_auto_20190121_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boards.Board'),
        ),
        migrations.AlterField(
            model_name='articleiplog',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Article'),
        ),
        migrations.AlterField(
            model_name='articleiplog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boards.Article'),
        ),
        migrations.AlterField(
            model_name='commentiplog',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Comment'),
        ),
        migrations.AlterField(
            model_name='commentiplog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
