# Generated by Django 2.1.5 on 2019-01-25 19:17

from django.db import migrations, models
import storages.backends.ftp
import tutorialPoll.custom_upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0040_auto_20190122_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='thumb',
            field=models.ImageField(null=True, storage=storages.backends.ftp.FTPStorage(), upload_to=tutorialPoll.custom_upload_path.custom_uploaded_filepath_deploy_thumb_image),
        ),
    ]
