# Generated by Django 2.1.5 on 2019-01-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0043_auto_20190126_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='attachment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='boards.Attachment'),
        ),
    ]
