# Generated by Django 2.1.5 on 2019-01-25 19:41

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.ftp
import tutorialPoll.custom_upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0044_auto_20190126_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='thumb',
        ),
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(null=True, storage=storages.backends.ftp.FTPStorage(), upload_to=tutorialPoll.custom_upload_path.custom_uploaded_filepath_deploy_thumb_image),
        ),
        migrations.AddField(
            model_name='attachment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='boards.Article'),
        ),
    ]
